### ISSUE TITLE
Why capitalize terms?

### ISSUE THREAD

**Issue by searchlie** [MaayanLab/blitzgsea#10]
I have been using gseapy to run GSEA in a python environment, but recently learned of your paper and became very interested.
So far, indeed, I am very happy with the results, as they almost reproduce gseapy's results.

However, I am puzzled by the behavior of capitalizing terms in libraries loaded from enrichr.
Why is this behavior necessary? Is there an option to turn this behavior off?

This makes it difficult to compare blitzgsea with enrichr or gseapy.

gseapy result:
![image](https://user-images.githubusercontent.com/28975498/235034122-71fb6f77-1907-4368-b23b-60e1282d6250.png)

blitzgsea result:
![image](https://user-images.githubusercontent.com/28975498/235034157-a0c501e5-f344-4a0d-9274-c22d45074108.png)

**Comment by lachmann12** [comment]
Good point! Thank you for mentioning it. I have updated the code to leave the gene set names as they are.
