### ISSUE TITLE
ValueError: Sample larger than population or is negative

### ISSUE THREAD

**Issue by MrOlm** [MaayanLab/blitzgsea#11]
Hello,

This is a super useful tool- thank you so much for developing!

I'm hitting a problem that when I run gsea on large samples, it works, but when I try and subset my big dataframe I run into the problem listed at the end of this message. I am running the `blitz.gsea` method.

I have done the test where I take my big dataframe and subset it until I hit this error and it usually happens around 40,000 rows or less, but other dataframes with more than 40,000 rows also hit this error.

Any insight into how I can get around this problem by adjusting the input parameters to `blitz.gsea`?

Thanks,
Matt

```RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/mattolm/miniconda3/envs/mamba/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/home/mattolm/miniconda3/envs/mamba/lib/python3.10/site-packages/blitzgsea/__init__.py", line 164, in estimate_anchor_star
    plt.plot(xx, yy, '--', lw=3)
  File "/home/mattolm/miniconda3/envs/mamba/lib/python3.10/site-packages/blitzgsea/__init__.py", line 167, in estimate_anchor
    yy = f_alpha_neg(xx)
  File "/home/mattolm/miniconda3/envs/mamba/lib/python3.10/site-packages/blitzgsea/__init__.py", line 72, in get_peak_size
  File "/home/mattolm/miniconda3/envs/mamba/lib/python3.10/random.py", line 482, in sample
    raise ValueError("Sample larger than population or is negative")
ValueError: Sample larger than population or is negative
"""

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
Cell In[139], line 16
     14     #tdb['iga_enrichment'] = tdb['iga_enrichment'] * 10
     15     tdb = tdb[['annos', 'iga_enrichment']].sort_values('iga_enrichment').rename(columns={'annos':0, 'iga_enrichment':1}).reset_index(drop=True)
---> 16     rdb = blitz.gsea(tdb, lib2)#, max_size=5, anchors=1)
     18 #     try:
     19 #         rdb = blitz.gsea(tdb, k2p)
     20 #     except:
     21 #         continue
     22     rdb['genome'] == genome

File ~/miniconda3/envs/mamba/lib/python3.10/site-packages/blitzgsea/__init__.py:241, in gsea(signature, library, permutations, anchors, min_size, max_size, processes, plotting, verbose, symmetric, signature_cache, seed)
    239     f_alpha_pos, f_beta_pos, f_pos_ratio, ks_pos, ks_neg = blitzgsea_signature_anchors[sig_hash]
    240 else:
--> 241     f_alpha_pos, f_beta_pos, f_pos_ratio, ks_pos, ks_neg = estimate_parameters(signature, abs_signature, signature_map, library, permutations=permutations, calibration_anchors=anchors, processes=processes, symmetric=symmetric, plotting=plotting, verbose=verbose, seed=seed)
    242     blitzgsea_signature_anchors[sig_hash] = (f_alpha_pos, f_beta_pos, f_pos_ratio, ks_pos, ks_neg)
    244 gsets = []

File ~/miniconda3/envs/mamba/lib/python3.10/site-packages/blitzgsea/__init__.py:96, in estimate_parameters(signature, abs_signature, signature_map, library, permutations, symmetric, calibration_anchors, plotting, processes, verbose, seed)
     94 with multiprocessing.Pool(jobs) as pool:
     95     args = [(signature, abs_signature, signature_map, xx, permutations, symmetric, seed+xx) for xx in x]
---> 96     results = list(tqdm(pool.imap(estimate_anchor_star, args), desc="Calibration", total=len(args)))
     98 alpha_pos = []
     99 beta_pos = []

File ~/miniconda3/envs/mamba/lib/python3.10/site-packages/tqdm/std.py:1195, in tqdm.__iter__(self)
   1192 time = self._time
   1194 try:
-> 1195     for obj in iterable:
   1196         yield obj
   1197         # Update and possibly print the progressbar.
   1198         # Note: does not call self.update(1) for speed optimisation.

File ~/miniconda3/envs/mamba/lib/python3.10/multiprocessing/pool.py:873, in IMapIterator.next(self, timeout)
    871 if success:
    872     return value
--> 873 raise value

ValueError: Sample larger than population or is negative```

**Comment by lachmann12** [comment]
Thank you for the feedback. Would you be able to safe the data frame that causes the error and send it to me by email. You can send it to alexander.lachmann@mssm.edu The error message might also help and i will investigate what is happening.

**Comment by lachmann12** [comment]
From the error message it also seems you are using an older version. I updated this part of the code very recently. I don't think it will necessarily fix it but it is worth trying to update.

**Comment by lachmann12** [comment]
The error should have been addressed in the latest version.

**Comment by lachmann12** [comment]
Also I would recommend not setting the anchors=1. The null models need to be calculated across multiple points to be accurate. With the new version calculating the default number of anchors is very fast

**Comment by MrOlm** [comment]
Thanks @lachmann12 ! Updating did indeed fix this problem, but I'm now hitting another bug with a different error code. I just finished making test data and will open a new issue with the data attached. 

Also thank you for your advice about the anchors- the only reason I moved from default was to try and fix this bug, but for my actual research have always left it at default

**Comment by lachmann12** [comment]
can you try to update these packages to these versions or higher?

loess==2.1.2
matplotlib==3.6.0
mpmath==1.2.1
mpsci==0.0.1.dev73
numpy==1.24.3
pandas==2.0.1
scipy==1.10.1
setuptools==58.0.4
statsmodels==0.13.2
tqdm==4.64.1

especially one of these might be the culprit:
loess==2.1.2
mpmath==1.2.1
mpsci==0.0.1.dev73

**Comment by lachmann12** [comment]
I was able to compute the two dataframes with the library from the zip file
