### ISSUE TITLE
Error with `shared_null=True`: erfinv(x) is defined only for -1 <= x <= 1

### ISSUE THREAD

**Issue by scottgigante-immunai** [MaayanLab/blitzgsea#13]
I'm getting an error in one of my many calls to `blitzgsea` when I set `shared_null=True` with the latest version.

```
result = blitzgsea.gsea(
  File "/Users/scottgigante/envs/immunaISR/lib/python3.8/site-packages/blitzgsea/__init__.py", line 338, in gsea
    nes = invcdf(mpf(1)-mpf(np.min([1,prob_two_tailed])))
  File "/Users/scottgigante/envs/immunaISR/lib/python3.8/site-packages/blitzgsea/mpsci.py", line 28, in invcdf
    a = mp.erfinv(2*p - 1)
  File "/Users/scottgigante/envs/immunaISR/lib/python3.8/site-packages/mpmath/ctx_mp_python.py", line 1023, in f_wrapped
    retval = f(ctx, *args, **kwargs)
  File "/Users/scottgigante/envs/immunaISR/lib/python3.8/site-packages/mpmath/functions/expintegrals.py", line 80, in erfinv
    return ctx.bad_domain("erfinv(x) is defined only for -1 <= x <= 1")
  File "/Users/scottgigante/envs/immunaISR/lib/python3.8/site-packages/mpmath/ctx_base.py", line 68, in bad_domain
    raise ValueError(msg)
ValueError: erfinv(x) is defined only for -1 <= x <= 1
```

It's not super straightforward for me to reprex, but hopefully the domain of this function should make for a self explanatory fix.

**Comment by lachmann12** [comment]
Hm, I did just add this to get rid of a dependency. But, it should have been the same. I just copy pasted the function. Should be possible to find the issue.

**Comment by lachmann12** [comment]
It should have been a numerical issue. The range is now forced into the right scale. Should be ok now.

**Comment by scottgigante-immunai** [comment]
Unfortunately still getting the same error.


[reprex.zip](https://github.com/MaayanLab/blitzgsea/files/11422726/reprex.zip)

```python
import pickle
import pandas as pd
import blitzgsea
import warnings

with open("reprex.pickle", "rb") as handle:
    blitzgsea.pdf_cache = pickle.load(handle)

library = {}
for gene_set in [
    "KEGG_2021_Human",
    "Reactome_2022",
]:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", message="unclosed file", category=ResourceWarning)
        library.update(blitzgsea.enrichr.get_library(gene_set))

input_df = pd.read_csv("reprex.csv")
blitzgsea.gsea(
    input_df,
    library,
    processes=1,
    shared_null=True,
    permutations=3, max_size=100, min_size=50
)
```

```shell
✗ pip freeze | grep blitzgsea
blitzgsea==1.3.26
```

**Comment by lachmann12** [comment]
ok, it will be fixed now hopefully... I also assume you are just testing out some parameter ranges, but the number of permutations needs to be much higher than 3 to be reliable. I would recommend not going below 1000.

**Comment by scottgigante-immunai** [comment]
Yes, just testing for speed purposes. Thanks!

**Comment by scottgigante-immunai** [comment]
[reprex.zip](https://github.com/MaayanLab/blitzgsea/files/11424451/reprex.zip)

Another one for you, failing with the same code above on `1.3.27`.

**Comment by lachmann12** [comment]
ok, at least i can reproduce the error :)

**Comment by lachmann12** [comment]
There is an underlying issue with the GSEA statistic in general which is not specific to the implementation. The null uses the peak heights of running sums. But when values are all positive in a signature, the ES value distribution gets skewed and does prohibit forming a proper null model. A solution is to center the signature value distribution around 0 before calculating the running sum. The new version centers by default now and produces good results on the example that was posted.

**Comment by scottgigante-immunai** [comment]
Looks resolved, thank you!
