### ISSUE TITLE
Inverted NES values

### ISSUE THREAD

**Issue by kohcl17** [MaayanLab/blitzgsea#19]
I was wondering if there may be a bug with the NES values. I tried the same dataset and code as the example provided but yielded a negative NES value despite the plot showing positive running sum values.

Nevertheless, I appreciate the faster GSEA processing! :)

Best regards,
Clara

![Screenshot 2023-06-07 at 3 09 29 PM](https://github.com/MaayanLab/blitzgsea/assets/91475711/91ab76cb-6263-465d-937f-7c65031e584a)

![Screenshot 2023-06-07 at 3 09 45 PM](https://github.com/MaayanLab/blitzgsea/assets/91475711/c6ad58c3-0cf4-4a5b-b5fe-4fdcb0a28e34)

**Comment by lachmann12** [comment]
Thank you for finding this bug. This bug was introduced when I updated the nes calculation. It should be fixed now in the latest version.
