### ISSUE TITLE
KeyError: 'xvalues'

### ISSUE THREAD

**Issue by scottgigante-immunai** [MaayanLab/blitzgsea#21]
Another error that I'm having a hard time reproing, but pops up from time to time when running in parallel.
```pytb
Trackback:
    result = blitzgsea.gsea(
  File "/home/jovyan/envs/immunaISR/lib/python3.8/site-packages/blitzgsea/__init__.py", line 288, in gsea
    kld, sig_hash_temp = best_kl_fit(np.array(signature["v"]), pdf_cache, bins=kl_bins)
  File "/home/jovyan/envs/immunaISR/lib/python3.8/site-packages/blitzgsea/signature_similarity.py", line 26, in best_kl_fit
    ipdf = map_density_range(xv, pdfs[k]["xvalues"], pdfs[k]["pdf"])
KeyError: 'xvalues'
```

**Comment by lachmann12** [comment]
that is quite odd. It is part of the KL test. pdfs is from the signature cache. It is surprising that there is a key error for xvalues.

`
pdf_cache[sig_hash] = {}
xv, pdf = create_pdf(np.array(signature["v"]), kl_bins)
pdf_cache[sig_hash]["xvalues"] = xv
pdf_cache[sig_hash]["pdf"] = pdf
pdf_cache[sig_hash]["model"] = (f_alpha_pos, f_beta_pos, f_pos_ratio, ks_pos, ks_neg)
`
is the only part where the cache gets updated. So why sig_hash is a key but xvalues isn't is odd
