### ISSUE TITLE
ES & NES signs are flipped

### ISSUE THREAD

**Issue by Hila-Sharim** [MaayanLab/blitzgsea#23]
Hello,
It seems that the normalized enrichment scores are opposite in sign to non-normalized enrichment scores (so positive becomes negatives and vice versa). I have also tried running the same data through `fgsea`, and there the sign is always kept (this is also intentional according to the description of their algorithm). 

Is the sign change in your implementation intentional?
Thanks!

**Comment by lachmann12** [comment]
Hi, is this with the latest version? There was an accidental sign flip in one of the subversions. In the latest it should be fixed. Could you try to update blitzgsea and let me know if you still experience the same issue?

**Comment by Hila-Sharim** [comment]
resolved by updating to the latest version. thanks!

**Comment by lachmann12** [comment]
Glad it was resolved. I am always happy for feedback!
