### ISSUE TITLE
Make interactive plotting optional

### ISSUE THREAD

**Issue by Zethson** [MaayanLab/blitzgsea#25]
Hi,

unfortunately, interactive plots do not go well with Jupyter notebooks and tutorials that render jupyter notebooks. Would it be possible to make interactive plotting optional?

Thank you very much!

**Comment by lachmann12** [comment]
Hi, could you explain this a bit more? Currently, blitzgsea only uses the matplotlib library, so there is no interactive plotting.

**Comment by Zethson** [comment]
This is where you enable interactive plotting: https://github.com/MaayanLab/blitzgsea/blob/main/blitzgsea/plot.py#L135 and https://github.com/MaayanLab/blitzgsea/blob/main/blitzgsea/plot.py#L184

**Comment by lachmann12** [comment]
Ha, I see. I will have a look if i can do without it.

**Comment by lachmann12** [comment]
I added an option to disable the interactive plotting switching. The plotting functions will then plot the figure. This should work like this (the old behavior is interactive_plot=False):

fig = blitz.plot.running_sum(signature, "Cell adhesion molecules", library, result=result, compact=False, interactive_plot=True)
fig_table = blitz.plot.top_table(signature, library, result, n=15, interactive_plot=True)

**Comment by Zethson** [comment]
Awesome! May I kindly request a new release?

Edit: Oh wait, I think you already made one, but it doesn't seem to work for me...

**Comment by Zethson** [comment]
So this is what I'm running:

```
            fig = blitzgsea.plot.top_table(
                adata.uns[key]["scores"][cluster],
                adata.uns[key]["targets"],
                enrichment[cluster],
                n=n,
                interactive_plot=interactive_plot
            )
            fig.suptitle(cluster)
            fig.show()
```

using `False` for interactive plotting I just get

```
[/home/zeth/PycharmProjects/pertpy/pertpy/tools/_enrichment.py:392](https://file+.vscode-resource.vscode-cdn.net/home/zeth/PycharmProjects/pertpy/pertpy/tools/_enrichment.py:392): UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  fig.show()
[/home/zeth/PycharmProjects/pertpy/pertpy/tools/_enrichment.py:392](https://file+.vscode-resource.vscode-cdn.net/home/zeth/PycharmProjects/pertpy/pertpy/tools/_enrichment.py:392): UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  fig.show()
[/home/zeth/PycharmProjects/pertpy/pertpy/tools/_enrichment.py:392](https://file+.vscode-resource.vscode-cdn.net/home/zeth/PycharmProjects/pertpy/pertpy/tools/_enrichment.py:392): UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  fig.show()
[/home/zeth/PycharmProjects/pertpy/pertpy/tools/_enrichment.py:392](https://file+.vscode-resource.vscode-cdn.net/home/zeth/PycharmProjects/pertpy/pertpy/tools/_enrichment.py:392): UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  fig.show()
[/home/zeth/PycharmProjects/pertpy/pertpy/tools/_enrichment.py:392](https://file+.vscode-resource.vscode-cdn.net/home/zeth/PycharmProjects/pertpy/pertpy/tools/_enrichment.py:392): UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  fig.show()
[/home/zeth/PycharmProjects/pertpy/pertpy/tools/_enrichment.py:392](https://file+.vscode-resource.vscode-cdn.net/home/zeth/PycharmProjects/pertpy/pertpy/tools/_enrichment.py:392): UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  fig.show()
[/home/zeth/PycharmProjects/pertpy/pertpy/tools/_enrichment.py:392](https://file+.vscode-resource.vscode-cdn.net/home/zeth/PycharmProjects/pertpy/pertpy/tools/_enrichment.py:392): UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  fig.show()
[/home/zeth/PycharmProjects/pertpy/pertpy/tools/_enrichment.py:392](https://file+.vscode-resource.vscode-cdn.net/home/zeth/PycharmProjects/pertpy/pertpy/tools/_enrichment.py:392): UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  fig.show()
```

and if I set it to True, I also get warnings but it plots some plots that absolutely should not be in there inline. Something is off I think

**Comment by Zethson** [comment]
Is it possible that you're also setting this elsewhere?

I am using blitzgsea 1.3.38

**Comment by Zethson** [comment]
Ahhh now I see. I'm supposed to set `interactive_plot` to `True`. I think that this is misleading. If I set it to `True` I expect to get interactive plotting and if I set it to False, I expect it to get disabled. Moreover, even when I set it to True, I still get

```
[/tmp/ipykernel_139902/1881904403.py:8](https://file+.vscode-resource.vscode-cdn.net/tmp/ipykernel_139902/1881904403.py:8): UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  fig.show()
```
