### ISSUE TITLE
randomness in blitz.gsea() results

### ISSUE THREAD

**Issue by jacqueline-alector** [MaayanLab/blitzgsea#27]
Hi, 

I've been using blitzgsea for a while now, and I noticed there was randomness in the output ranked pathway result table. The p-values for the enriched pathway were not stable, and setting seed within the .gsea() function would not help. 
To solve this issue, I had to set an additional seed prior to running the function.

```
np.random.seed(123)
use_lib = 'KEGG_2021_Human'
f = files[0]
signature = pd.read_csv(os.path.join(root_dir,f), sep='\t')
gsea_lib = blitz.enrichr.get_library(use_lib)
gsea= blitz.gsea(signature, 
                 gsea_lib,
                 seed=123) 
```
If I took out `np.random.seed(123)`, then gsea results would not be stable.

**Comment by lachmann12** [comment]
Thank you for pointing this out. I added the numpy seed to the gsea function. (if the seed is -1 it will be randomly generated)
