### ISSUE TITLE
GeneSigDB term names

### ISSUE THREAD

**Issue by alexlenail** [MaayanLab/blitzgsea#3]
Thanks for making this package available. 

What are the terms in the gene set `GeneSigDB` ? My top enriched terms are e.g.

```
17150101-TABLES1L
18387200-GENES
19139136-TABLES3
17899371-GENETABLE4
19798054-ST
```

Which are pretty difficult to interpret.

**Comment by AviMaayan** [comment]
The numbers are PubMed IDs... For example: https://pubmed.ncbi.nlm.nih.gov/17150101/

**Comment by alexlenail** [comment]
Thanks for replying @AviMaayan 

Is there a table of gene sets available from GeneSigDB with human readable names? I noticed enrichr also uses these gene set IDs:

<img width="220" alt="image" src="https://user-images.githubusercontent.com/2761597/193131908-619fef34-4778-43d4-b236-01f89e609ca5.png">

**Comment by AviMaayan** [comment]
We do not have it. This library was created many years ago and the original resource (GeneSigDB) is no longer available. You can try using NCBI e-utils https://www.ncbi.nlm.nih.gov/books/NBK25497/ to get the titles of the papers given their PMID.
