### ISSUE TITLE
FitDataError: Invalid values in `data` for gamma.fit

### ISSUE THREAD

**Issue by yihming** [MaayanLab/blitzgsea#30]
Hello,

I encounter an issue when using `blitz.gsea` function with `symmetric=True`:
```
FitDataError: Invalid values in `data`.  Maximum likelihood estimation with 'gamma' requires that 0 < (x - loc)/scale  < inf for each x in `data`.
```
The error message points to this line: https://github.com/MaayanLab/blitzgsea/blob/main/blitzgsea/__init__.py#L208.

To further diagnose the issue, I found that it was because `aes` array contains `0`, while `gamma.fit` requires all positive values. However, as `permutations` get larger (by default it's `2000` already large enough to trigger the issue), it's to some extend inevitable to have zero values for ES.

I was wondering if I misunderstood somewhere on your algorithm, or had something wrong in my set up. 

Look forward to your help. Thanks!

P.S.: This issue occurs in some of my datasets, while my other data worked properly. Also, it happens when I choose Wald test statistics as the signature, while log2FC may work well.

Sincerely,
Yiming

**Comment by yihming** [comment]
I then set `symmetric=False`, hoping to go around the issue above. However, now I got the following error:
```
ValueError: The function value at x=nan is NaN; solver cannot continue.
```
which points to this line: https://github.com/MaayanLab/blitzgsea/blob/main/blitzgsea/__init__.py#L223.

This is still related to `gamma.fit` function, which emits the error message above when it gets an empty array, e.g. `es` has no negative scores.

How should I handle this case?

**Comment by lachmann12** [comment]
Hi, thank you for brining up the issue. It is difficult to reproduce this issue, and it must have something to do with the value distribution in the signature you have. I updated the blitzgsea version to handle 0 es values. However this is probably not the issue. `es` values should by definition never be 0 as it is the maximum deviation from 0 on a running sum. I removed the premature return when sum_hit_scores == 0. It seems the only part that I can think of that returns 0, and should actually also never be true. The latest version is 1.3.42 and can be downloaded with pip.

If you could share the example signature i could reproduce the problem if this didn't solve it.

Best,
Alex

```
def enrichment_score_null(abs_signature, hit_indicator, number_hits):
    np.random.shuffle(hit_indicator)
    hits = np.where(hit_indicator == 1)[0]
    number_miss = len(abs_signature) - number_hits
    sum_hit_scores = np.sum(abs_signature[hits])
    if sum_hit_scores == 0:
        return 0
    norm_hit = 1.0/sum_hit_scores
    norm_no_hit = 1.0/number_miss
    running_sum = np.cumsum(hit_indicator * abs_signature * norm_hit - (1 - hit_indicator) * norm_no_hit)
    peak = np.abs(running_sum).argmax()
    es = running_sum[peak]
    return es
```

**Comment by yihming** [comment]
Thank you so much for fixing the issue so quickly.

The latest version has no more error when processing my data's signature. However, in the result data frame, some of the terms have `-Inf` NES scores, while their p-values and fdr are `0.0`. Should I ignore such terms?


Sincerely,
Yiming

**Comment by lachmann12** [comment]
Hi,

Glad the fix worked for you!

I am still actively searching the cause of these infinities. It could be the case if the enrichment is extremely high. There are some numeric instabilities for very small p-values. The p-value is computed from the NES, so if the NES is inf/-inf it defaults to a 0 p-value. But this does not mean the enrichment is actually significant. If I remember correctly, the opposite is the case, so for now i would just remove them.

Best,
Alex
