### ISSUE TITLE
runtime error in running blitzgsea

### ISSUE THREAD

**Issue by robinpaul85** [MaayanLab/blitzgsea#32]
Ran
signature = pd.read_csv("https://github.com/MaayanLab/blitzgsea/raw/main/testing/ageing_muscle_gtex.tsv")                                                   
blitz.enrichr.print_libraries()                                         
library = blitz.enrichr.get_library("KEGG_2021_Human")                                                       
result = blitz.gsea(signature, library, shared_null=True)

I get the following error:

File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/multiprocessing/spawn.py", line 140, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

        To fix this issue, refer to the "Safe importing of main module"
        section in https://docs.python.org/3/library/multiprocessing.html

Can you please suggest how to fix this error?

**Comment by lachmann12** [comment]
I have added something that might fix it, but I am not sure since the error does not occur for me. The error might be operating system dependent, and I have only tested it on macos. There is an updated version 1.3.43 you can try. Let me know if it fixed it.

**Comment by robinpaul85** [comment]
I tried the updated version, but I still get the same error. I noticed that when I set `result = blitz.gsea(signature, library, processes=1)` it works. But I cannot get it to work using multiprocessors (default=4). I am also using macos.

I am using Python 3.11.6. Can you test it using this version?

**Comment by lachmann12** [comment]
Hm, in what environment are you running it. I just tested it with Python 3.9.6 and also 3.12.3 and don't get the issue. I tested it in jupyter notebook and in the Python console.

**Comment by robinpaul85** [comment]
ok, I can get it running from a python console. But when I copy the commands to a file for e.g. test.py and run it (`$python test.py`) I get that error . But it works from the python console. 

When I replace to `result = blitz.gsea(signature, library, processes=1)` it works through test.py

**Comment by lachmann12** [comment]
A fix on your side can be to make sure the script runs in main:

```
import blitzgsea as blitz
import pandas as pd

signature = pd.read_csv("https://github.com/MaayanLab/blitzgsea/raw/main/testing/ageing_muscle_gtex.tsv")
library = blitz.enrichr.get_library("GO_Biological_Process_2023")

if __name__ == "__main__":
    result = blitz.gsea(signature, library, permutations=2000)
    print(result)
```

this will work without error. I am trying to find a way to make it work without this, but in general this would be good practice when running python scripts.

**Comment by lachmann12** [comment]
i tried a lot of ways to mitigate, but did not find anything that would work. I update the docs to include `if __name__ == "__main__":`. This will work in any case, whether users use jupyter notebooks or run the code in a script.
