### ISSUE TITLE
How to handle FDR of 0 and -inf/inf NES?

### ISSUE THREAD

**Issue by benwilks** [MaayanLab/blitzgsea#33]
Hello! First, thank you for the blitzgea package! 

I just have a question about the best way of handling FDR=0 and NES of -inf/inf. It doesn't seem like changing the number of permutations (2k - 100k) has any effect on the number of gene sets that yield FDR=0 and NES=-inf/inf. Are there other parameters that can be tuned to reduce the number of gene sets that yield those values? If not, how do you generally go about visualization of results since I've generally seen GSEA summary results displayed as dot plots, bar plots, etc. Do you recommend just setting the FDR = min(FDR) and NES similarly?

I'm currently using gene collections from MSigDB and running:
`result = blitz.gsea(signature, collection, permutations=self.permutations, processes=4, verbose=verbose, progress=progress)`

with permutations ranging from 2k to 100k.

**Comment by lachmann12** [comment]
There is some error that is caused by numerical instability. I am searching for it, but have not found a fix for it. I hope to be able to find and fix it soon.

**Comment by lachmann12** [comment]
I have found the cause of the numeric instability. this happened when some of the internal statistics approached 1 and had to be rounded to float, resulting in exactly 1. The fix should now result in nearly arbitrary small p-value support. There is a parameter called deep_accuracy which could also be increased in case there are issues (should not be needed in practice).

**Comment by benwilks** [comment]
@lachmann12 thank you for the quick response and solution!
