### ISSUE TITLE
Is it possible to run multiple signatures in parallel? 

### ISSUE THREAD

**Issue by alexlenail** [MaayanLab/blitzgsea#5]
Say I have 1000 gene expression signatures -- would it be possible to run them faster than sequentially? I notice there's a calibration step before each enrichment step -- could that step be performed just once?

**Comment by lachmann12** [comment]
The calibration is for the value distribution of a given signature. If the signatures have different values, then technically a calibration would be required for each signature. I could add a flag that can skip the calibration. It would probably be fine.

**Comment by alexlenail** [comment]
I'd appreciate that! Each of my signatures is different but they all share an identical range / nearly identical distribution, so I'd like to only compute it once (takes quite a while otherwise)

**Comment by lachmann12** [comment]
The function `blitzgsea.gsea` now has a parameter called `shared_null`. By default False, if set to True will reuse the null. Hope this does the trick.
