### ISSUE TITLE
two gene sets GSEA, DGSEA module

### ISSUE THREAD

**Issue by abearab** [MaayanLab/blitzgsea#7]
Is there any chance that you can implement DGSEA in python as part of your package?

- https://academic.oup.com/bioinformatics/article/36/21/5247/5874441
- https://jamesjoly.github.io/DGSEA/about/
- https://github.com/JamesJoly/DGSEA (developed by @JamesJoly in R)

**Comment by lachmann12** [comment]
There is currently no plan to implement a wider range of GSEA variants. Maybe in the future. Best, Alex
