### ISSUE TITLE
Running blitzgsea with more than one signature at a time

### ISSUE THREAD

**Issue by scottgigante-immunai** [MaayanLab/blitzgsea#8]
I love how much faster your package is than gseapy -- however, the benefit is lost when I run more than one gene set at a time. By my measure, running `blitzgsea.gsea` on one signature for my particular dataset takes ~20s; running `gseapy.prerank` on all 32 signatures at once takes 8 minutes. By the time I run blitzgsea 32 times of course, this comes out to ~10m -- which ends up being slower. I suspect there are some efficiencies lost by naively running your code back-to-back 32 times. Is there any chance you would consider refactoring to support multiple signatures in the input dataframe?

**Comment by lachmann12** [comment]
If you run a lot of signatures and their value distributions are somewhat comparable, I would highly recommend using the parameter `shared_null=True`. This way you will get results instantly. For most of my use cases, I get more or less identical results

**Comment by scottgigante-immunai** [comment]
Thanks! Would it make sense to e.g. run the `estimate_parameters` function on some combined meta-signature to get an average distribution rather than simply the first one?

**Comment by lachmann12** [comment]
It is a bit tricky to optimize it in that way. I have however spent some time looking more closely at the null generation, and there have been some opportunities for improvement. The calibration time is now down from 20+ sec to around 3 sec which is pretty nice if dealing with multiple signatures and you don't want to share the null model between them.

The idea of the meta-signature is not bad. You can also do this yourself, by calculating an average signature, run it through blitzgsea and then use the shared_null. It should then use that model. I will see if I can add some function to do these things automatically in the future.

**Comment by scottgigante-immunai** [comment]
Thanks @lachmann12, this is very helpful! One challenge with the current implementation is that I have multiple sets of signatures -- within a set I trust that the distributions are similar, but between sets I do not. So it would be nice to be able to specify _which_ shared null to use.

**Comment by lachmann12** [comment]
I was already thinking of a solution based on KL-divergence. It should be possible to decide based on distribution similarity whether nulls are compatible. I will definitely implement it and see how well it works.

**Comment by scottgigante-immunai** [comment]
Oooh, clever! Thanks!

**Comment by lachmann12** [comment]
ok, it works well. I did some testing and it seems quite robust. The sensitivity can be tuned with the kl_threshold parameter. Lower means more stringent. When shared_null is true it will automatically do the KL testing.

**Comment by scottgigante-immunai** [comment]
Thanks @lachmann12 for the rapid upgrade. This is great!
